name: strukcode

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  strukcode:
    if: |
      contains(github.event.comment.body, ' /oc') ||
      startsWith(github.event.comment.body, '/oc') ||
      contains(github.event.comment.body, ' /strukcode') ||
      startsWith(github.event.comment.body, '/strukcode')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: read
      issues: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-bun

      - name: Run strukcode
        uses: harutk7/strukcode/github@latest
        env:
          STRUKCODE_API_KEY: ${{ secrets.STRUKCODE_API_KEY }}
        with:
          model: strukcode/claude-haiku-4-5
